name: update-dict

on:
  schedule:
    - cron: "30 0 */1 * *"
  workflow_dispatch:
    inputs:
      commit_message:
        description: "Commit Message"
        type: string
        required: false

jobs:
  update-dict-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: true
      - name: Fetch and Download Latest zhwiki.dict.yaml
        run: |
          latest_asset=$(curl -s https://api.github.com/repos/felixonmars/fcitx5-pinyin-zhwiki/releases/tags/0.3.0 \
          | jq -r '.assets[] | select(.name | test("zhwiki-[0-9]{8}\\.dict")) | .browser_download_url' \
          | sort -r | head -n 1)
          wget "$latest_asset" -O zhwiki-20230507.dict.yaml
      - id: moegirl
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: outloudvi/mw2fcitx
      - name: Add files to git
        id: add_files
        run: |
          git config user.name "ahxxm[rime-bot]"
          git config user.email "rime-bot@ahxxm.com"
          wget -O moegirl.dict.yaml "https://github.com/outloudvi/mw2fcitx/releases/download/${{ steps.moegirl.outputs.release }}/moegirl.dict.yaml"
          git add .
          commit_msg="${{ github.event.inputs.commit_message }} - update dictionary"
          git commit -m "$commit_msg" || echo "nothing to commit"
          git pull origin $(git rev-parse --abbrev-ref HEAD) --unshallow --rebase
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
